"""Narration for c3-03-everyone-gets-a-menu: generated by _tools/narration.py from video-script.md.

One caption per spoken piece, in SPOKEN form; `pauses[i]` is the silence after caption i.
Do not edit: change the script and run the tool again.
"""
NAME = "c3_03"

SHOTS = [
    {
        "id": "s01_cold_open",
        "title": 'Cold open',
        "frames": 624,
        "captions": [
            ('Same room. Same moment.', 0, 52),
            ('Two different menus.', 66, 105),
            ("The doctor can read something the engineer cannot, and neither of them can open the captain's log alone.", 118, 353),
            ('That is the whole trick of a boarding party, and it is one word and one semicolon.', 367, 588),
        ],
        "pauses": [0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s02_a_choice_for_one_job",
        "title": 'A choice for one job',
        "frames": 990,
        "captions": [
            ('A choice you already know, with two things added. if medical: only someone whose job is medical is offered it.', 0, 261),
            ('That word is the one on Roles in your roster.', 274, 405),
            ('Then a semicolon, and learn suits: when she takes it, the party knows a fact, and I have named it suits.', 418, 692),
            ('And the choice needs somewhere to go: a short room that says what she found, with one way back.', 706, 954),
        ],
        "pauses": [0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s03_the_other_job",
        "title": 'The other job',
        "frames": 297,
        "captions": [
            ('The same again for the engineer.', 0, 78),
            ('Now each of my two people has one thing only they can read.', 92, 261),
        ],
        "pauses": [0.45, 1.2],
    },
    {
        "id": "s04_a_door_that_opens_when_they_",
        "title": 'A door that opens when they know enough',
        "frames": 650,
        "captions": [
            ('learned is a number: how many different facts the party has.', 0, 143),
            ('The party, not the person.', 157, 222),
            ('So this choice appears for everyone once the surgeon and the engineer have each done their part.', 236, 457),
            ('And a fact counts once, however many times they read it.', 471, 614),
        ],
        "pauses": [0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s05_a_line_that_changes",
        "title": 'A line that changes',
        "frames": 755,
        "captions": [
            ('A party that walks here first finds a locked log.', 0, 130),
            ('If I say nothing, they think the game is broken.', 144, 274),
            ('So two versions of the line, and a condition in curly brackets on each.', 288, 470),
            ('Too early, they are told there is more to find.', 484, 614),
            ('Later, they are told it is time.', 628, 719),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s06_three_rules_and_lint",
        "title": 'Three rules, and lint',
        "frames": 1113,
        "captions": [
            ('Three rules.', 0, 30),
            ('Nobody gets an empty menu, so every room keeps a choice with no if.', 44, 226),
            ('A reading goes somewhere and comes back.', 240, 331),
            ('And count your facts: two facts, and the log asks for two. Lint. Clean.', 344, 527),
            ('It catches a misspelled learn.', 541, 606),
            ('It catches the sign the wrong way round.', 619, 724),
            ('It does not catch a misspelled job.', 737, 828),
            ('That one you check by eye: every word after if is learned, or a job from your roster.', 842, 1077),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s07_play_it",
        "title": 'Play it',
        "frames": 904,
        "captions": [
            ('Two people.', 0, 30),
            ('The doctor has it; the chief does not.', 44, 148),
            ('Straight to the bridge: locked, and it says so. Back. She reads. Aft. He reads.', 161, 357),
            ('Forward: and there it is.', 371, 436),
            ('Now watch what happens when the doctor stays home.', 449, 567),
            ('Same room, one person, and her reading comes to me, marked: covering for medical.', 580, 763),
            ('A short crew still finishes the story.', 776, 868),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s08_your_turn",
        "title": 'Your turn',
        "frames": 768,
        "captions": [
            ('Your third crew member has a job you made up.', 0, 130),
            ('Give them a reading on the bridge.', 144, 235),
            ('Leave the log at two, and now any two of three will open it: more than one way through.', 249, 497),
            ("Next time, we ask not only what someone's job is, but how good they are at it.", 510, 732),
        ],
        "pauses": [0.45, 0.45, 0.45, 1.2],
    },
]
