"""Narration for c3-02-party-and-place: generated by _tools/narration.py from video-script.md.

One caption per spoken piece, in SPOKEN form; `pauses[i]` is the silence after caption i.
Do not edit: change the script and run the tool again.
"""
NAME = "c3_02"

SHOTS = [
    {
        "id": "s01_cold_open",
        "title": 'Cold open',
        "frames": 572,
        "captions": [
            ('My engineer, three rooms, and a hulk nobody has opened in years.', 0, 157),
            ('She is the same person on the bridge and aboard it, and all of it is text I wrote in one file.', 170, 457),
            ('Today you write your own.', 470, 536),
        ],
        "pauses": [0.45, 0.45, 1.2],
    },
    {
        "id": "s02_your_crew",
        "title": 'Your crew',
        "frames": 1030,
        "captions": [
            ('A new section at the bottom.', 0, 78),
            ('The word crew on the first line of the fence says what it is.', 92, 274),
            ('Ship says whose crew.', 288, 340),
            ('And Names: locked says these are my people: without it, a player who has saved their own name keeps it.', 354, 614),
            ('Then one record per person: the console they sit at, a face, and a job.', 628, 824),
            ('Whoever sits at Engineering is the Chief, here and aboard the hulk.', 837, 994),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s03_the_place",
        "title": 'The place',
        "frames": 873,
        "captions": [
            ('A room is a record.', 0, 65),
            ('One line starting with a percent sign: what the party finds when they walk in.', 79, 274),
            ('Then the ways out.', 288, 340),
            ('Words in square brackets are what the crew reads.', 354, 471),
            ('The key in round brackets is the room it leads to.', 484, 628),
            ('And empty round brackets lead nowhere: that choice ends the visit and sends everyone home.', 641, 837),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s04_two_rules",
        "title": 'Two rules',
        "frames": 859,
        "captions": [
            ('Two rules, and they are the difference between a place and a trap.', 0, 170),
            ('Every room has a way back.', 183, 261),
            ('Every room has a way home.', 275, 353),
            ('Check them by eye, because lint only helps with half of it: it warns if a choice points at a room that does not exist, and says nothing about a room with no way out.', 367, 823),
        ],
        "pauses": [0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s05_start_it",
        "title": 'Start it',
        "frames": 1317,
        "captions": [
            ('Something has to say when.', 0, 65),
            ('Our quest already knows the moment: the ship is alongside.', 79, 209),
            ('So the quest sends a signal when it completes, and this card listens for it.', 223, 418),
            ('You paste it; you do not write it.', 432, 536),
            ('One line reads the rooms.', 550, 615),
            ('And one line runs the whole visit: it opens the party, starts the first room, and when the last choice is taken it brings everyone home.', 628, 968),
            ('Three things on the card are yours to change: the signal name, the name of the place, and the room they arrive in.', 981, 1281),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s06_check_it",
        "title": 'Check it',
        "frames": 197,
        "captions": [
            ('Lint. Clean.', 0, 30),
            ('And here is the one mistake it does catch.', 44, 161),
        ],
        "pauses": [0.45, 1.2],
    },
    {
        "id": "s07_play_it",
        "title": 'Play it',
        "frames": 480,
        "captions": [
            ('Engineering, and I am Chief Okoro. Alongside.', 0, 91),
            ('The quest completes, and the party forms. Down. The airlock. Aft. Back. Forward. Back.', 105, 287),
            ('And home: I did not press anything to get back here.', 301, 444),
        ],
        "pauses": [0.45, 0.45, 1.2],
    },
    {
        "id": "s08_your_turn",
        "title": 'Your turn',
        "frames": 454,
        "captions": [
            ('Add a fourth room, and a third person for Helm.', 0, 130),
            ('Give the room a way in, a way back and a way home.', 144, 314),
            ('Next time, everyone gets their own menu.', 327, 418),
        ],
        "pauses": [0.45, 0.45, 1.2],
    },
]
