"""Narration for c2-08-siege-boss: generated by _tools/narration.py from video-script.md.

One caption per spoken piece, in SPOKEN form; `pauses[i]` is the silence after caption i.
Do not edit: change the script and run the tool again.
"""
NAME = "c2_08"

SHOTS = [
    {
        "id": "s01_cold_open",
        "title": 'Cold open',
        "frames": 559,
        "captions": [
            ('This is the Corsair Queen.', 0, 65),
            ('She is not in the game you downloaded.', 79, 183),
            ('I wrote her this morning, in one small text file, without writing any code.', 197, 379),
            ('In the next fourteen minutes you will write your own.', 393, 523),
        ],
        "pauses": [0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s02_what_a_boss_is",
        "title": 'What a boss is',
        "frames": 677,
        "captions": [
            ('In Siege, raiders attack your starbases.', 0, 78),
            ('If you choose a boss, then when the raiders are nearly beaten, something worse arrives.', 92, 287),
            ('Four bosses come with the game.', 301, 379),
            ('Each one is a single file in a folder.', 393, 510),
            ('Add a file, and you have added a boss.', 524, 641),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s03_read_the_warlord",
        "title": 'Read the Warlord',
        "frames": 1109,
        "captions": [
            ('Here is the Warlord.', 0, 52),
            ('Two records, the shape you already know: a heading, a fence, a body.', 66, 235),
            ('The first record is the boss.', 249, 327),
            ('Boss says what kind of record it is.', 341, 445),
            ('Trigger and Low say when she arrives: when a quarter of the raiders are left.', 458, 654),
            ('Flies and Fleets say what comes with her.', 668, 772),
            ('Difficulty: +1 makes her one step harder than the game.', 785, 916),
            ('Named is her flagship: a name, then which ship it is.', 929, 1073),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s04_make_the_copy",
        "title": 'Make the copy',
        "frames": 664,
        "captions": [
            ('Never edit the Warlord. Copy it.', 0, 78),
            ("And not into the game's folder.", 92, 170),
            ("The game's folder is replaced every time the game is updated.", 184, 327),
            ('Yours is here: common data, bosses.', 341, 419),
            ('The Siege reads both.', 432, 484),
            ('Lowercase, underscores, no spaces, and keep dot A M D on the end.', 498, 628),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s05_rename_the_boss_and_the_flag",
        "title": 'Rename the boss and the flagship',
        "frames": 1187,
        "captions": [
            ('Square brackets are what the crew reads.', 0, 91),
            ('Round brackets are the key; match your file name." "Two traps.', 105, 248),
            ('Lint catches both, and you will see that in a minute, but know them now.', 262, 457),
            ('First: if you forget to change the name in square brackets, you get two Warlords and the list shows only one.', 471, 745),
            ("Second: the flagship's name is one word.", 758, 850),
            ("Type 'Iron Duke' and the game reads a ship called Iron, of a kind called Duke.", 863, 1072),
            ('There is no such ship.', 1085, 1151),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s06_write_her_words",
        "title": 'Write her words',
        "frames": 781,
        "captions": [
            ('Now the part you are here for.', 0, 91),
            ('One line for her entrance.', 105, 170),
            ('Then the objective: a new name, a new key, what it pays, and what you want the crew to read.', 184, 444),
            ('Leave the five lines in between alone today.', 458, 562),
            ('Plain quotes and plain hyphens only; the game cannot draw the curly kind.', 576, 745),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s07_check_it",
        "title": 'Check it',
        "frames": 759,
        "captions": [
            ('Two checks.', 0, 30),
            ('No squiggles in the editor.', 44, 109),
            ('Then lint, pointed at my own folder, so it checks my bosses and nothing else.', 122, 318),
            ("You want the word 'clean'.", 331, 397),
            ("Here is what it says if I put 'Iron Duke' back: it tells me what the game will read, and what to write instead.", 410, 723),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s08_see_her_in_the_list",
        "title": 'See her in the list',
        "frames": 598,
        "captions": [
            ('Start the server, choose Siege, open the Boss list.', 0, 117),
            ('There she is.', 131, 170),
            ('If she is not, the file is in the wrong folder, or the mission was already running when you saved.', 184, 444),
            ('The list is read when the mission starts.', 458, 562),
        ],
        "pauses": [0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s09_meet_her",
        "title": 'Meet her',
        "frames": 768,
        "captions": [
            ('At twenty-five percent you would fight for a long time before she shows up.', 0, 183),
            ('For testing, set it to ninety.', 196, 274),
            ('Now she comes after the first kills.', 288, 379),
            ('There is the Morrigan, there are her escorts, and there is your objective, in your words.', 393, 601),
            ('Put Low back to twenty-five when you are done.', 615, 732),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 1.2],
    },
    {
        "id": "s10_keep_it_safe_and_your_turn",
        "title": 'Keep it safe, and your turn',
        "frames": 847,
        "captions": [
            ('This is why she lives here.', 0, 78),
            ('Update the game and this folder is left alone.', 92, 209),
            ('It is still one file on one computer, so keep a copy, the way you would with a manuscript.', 223, 470),
            ('Now make a second boss, from your own story.', 484, 601),
            ('The page has the steps and a checklist.', 615, 719),
            ('Next time, we change the numbers.', 733, 811),
        ],
        "pauses": [0.45, 0.45, 0.45, 0.45, 0.45, 1.2],
    },
]
